// Generates (one line's case of) vectors/shielded/divaddr.json: Sapling diversified addresses of one
// viewing key, as a node wallet issued them and as sapling-crypto 0.7 derives them offline
// (tools/x4m/rust `divaddr`). The offline issuer (packages/ycash/src/shielded/sapling) must reproduce
// every address, so the vectors tie it to the node and to the Rust library at once.
//
//   cargo build --release --manifest-path tools/x4m/rust/Cargo.toml --bin divaddr
//   npx tsx vectors/shielded/divaddr-generate.ts --line dd|6 --devnet <devnet.json> --divaddr <bin> [--node 2]
//
// It makes a fresh Sapling key on the node (z_getnewaddress sapling), exports its viewing key, and
// asks the wallet for three diversified addresses. Running it again for a line replaces that line's case.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { YcashRpc } from "../../packages/ycash/src/index.js";
import { bech32Decode, bech32Encode } from "../../packages/ycash/src/shielded/sapling/index.js";

interface Derived {
  index: string;
  address: string;
}
interface LineCase {
  line: string;
  node: string;
  network: string;
  viewingKey: string;
  /** what the wallet returned: z_getnewaddress, then z_getnewdiversifiedaddress ×3, with the index divaddr finds them at */
  nodeAddresses: (Derived & { rpc: string })[];
  /** divaddr <key> <start> <count> */
  rust: { start: string; count: number; addresses: Derived[] }[];
}

const arg = (name: string, fallback?: string): string => {
  const i = process.argv.indexOf(`--${name}`);
  const v = i >= 0 ? process.argv[i + 1] : fallback;
  if (v === undefined) throw new Error(`--${name} is required`);
  return v;
};
const line = arg("line");
const rpc = YcashRpc.fromDevnetJson(arg("devnet"), Number(arg("node", "2")));
const divaddrBin = arg("divaddr");

const divaddr = (key: string, start: bigint, count: number): Derived[] =>
  execFileSync(divaddrBin, [key, start.toString(), String(count)], { encoding: "utf8" })
    .trim()
    .split("\n")
    .map((l) => {
      const [index, address] = l.split(" ");
      return { index: index as string, address: address as string };
    });

const base = await rpc.call<string>("z_getnewaddress", ["sapling"]);
const viewingKey = await rpc.call<string>("z_exportviewingkey", [base]);
const diversified: string[] = [];
for (let i = 0; i < 3; i++) diversified.push(await rpc.call<string>("z_getnewdiversifiedaddress", [base]));
const version = (await rpc.call<{ subversion: string }>("getnetworkinfo")).subversion;

const starts: [bigint, number][] = [
  [0n, 12],
  [1n << 40n, 4],
  [(1n << 63n) + 12345n, 2], // divaddr parses a u64
];
const rust = starts.map(([start, count]) => ({ start: start.toString(), count, addresses: divaddr(viewingKey, start, count) }));
const low = rust[0]?.addresses ?? [];
const nodeAddresses = [base, ...diversified].map((address, i) => {
  const hit = low.find((d) => d.address === address);
  if (!hit) throw new Error(`the node's ${address} is not among divaddr's first ${low.length} addresses`);
  return { rpc: i === 0 ? "z_getnewaddress sapling" : "z_getnewdiversifiedaddress", ...hit };
});

const out = join(dirname(fileURLToPath(import.meta.url)), "divaddr.json");
const doc = existsSync(out)
  ? (JSON.parse(readFileSync(out, "utf8")) as { description: string; cases: LineCase[]; mainnet?: unknown })
  : { description: "", cases: [] as LineCase[] };
doc.description =
  "Sapling diversified addresses of a viewing key: as each node line's wallet issued them, and as sapling-crypto 0.7 derives them offline " +
  "(tools/x4m/rust divaddr). Generated by vectors/shielded/divaddr-generate.ts. `mainnet` re-encodes the first key under the mainnet HRP.";
doc.cases = [...doc.cases.filter((c) => c.line !== line), { line, node: version, network: "ycash:regtest", viewingKey, nodeAddresses, rust }];
// Mainnet: the same key bytes under `zxviews`, so the mainnet HRPs are covered without a mainnet wallet.
const first = doc.cases[0] as LineCase;
const mainKey = bech32Encode("zxviews", bech32Decode(first.viewingKey).bytes);
doc.mainnet = { viewingKey: mainKey, rust: [{ start: (1n << 40n).toString(), count: 3, addresses: divaddr(mainKey, 1n << 40n, 3) }] };
writeFileSync(out, JSON.stringify(doc, null, 2) + "\n");
console.log(`${line}: ${nodeAddresses.map((a) => a.index).join(", ")} → ${out}`);
