"""vectors/shielded/shielded.json, generated by the TypeScript package: the request hash and memo,
JCS, and the ES256K receipts. Signing is deterministic on both sides (RFC 6979, low-S), so a JWS
signed here is byte-identical to TypeScript's, and each side verifies the other's."""

import pytest

from tests.conftest import load_vector
from x402_ycash.shielded.jcs import jcs
from x402_ycash.shielded.receipt import (
    create_jws,
    did_jwk_for,
    es256k_signer,
    public_key_from_did_jwk,
    sign_offer,
    sign_receipt,
    verify_jws,
    verify_receipt,
)
from x402_ycash.shielded.request import memo_for_record, memo_to_hex, request_hash

DOC = load_vector("shielded/shielded.json")
KEY = DOC["receiptKey"]
SIGNER = es256k_signer(KEY["priv"])


def test_request_hash_and_memo():
    r = DOC["request"]
    assert jcs(r["record"]) == r["jcs"]
    assert request_hash(r["record"]) == r["requestHash"]
    assert memo_for_record(r["record"]) == r["memo"]
    assert memo_to_hex(r["memo"]) == r["memoHex"]


@pytest.mark.parametrize("case", DOC["jcs"], ids=range(len(DOC["jcs"])))
def test_jcs_cases(case):
    assert jcs(case["value"]) == case["jcs"]


def test_kid_is_the_did_jwk_of_the_key():
    assert SIGNER.kid == KEY["kid"] == did_jwk_for(bytes.fromhex(KEY["pubCompressed"]))
    assert public_key_from_did_jwk(KEY["kid"]).hex() == KEY["pubCompressed"]
    assert public_key_from_did_jwk(KEY["kid"] + "#0").hex() == KEY["pubCompressed"]


def test_receipt_signed_here_is_byte_identical_to_typescripts():
    i = DOC["receipt"]["input"]
    mine = sign_receipt(i["network"], i["resourceUrl"], i["transaction"], SIGNER, issued_at=i["issuedAt"])
    assert mine == DOC["receipt"]["artifact"]
    assert sign_offer({k: v for k, v in _offer_payload().items() if k != "version"}, SIGNER) == DOC["offer"]["artifact"]
    assert create_jws(DOC["jws"]["payload"], SIGNER) == DOC["jws"]["compact"]


def test_typescript_receipt_verifies_here():
    p = verify_receipt(DOC["receipt"]["artifact"], [KEY["pubCompressed"]])
    assert p == {"version": 1, "payer": "anonymous", **DOC["receipt"]["input"]}
    with pytest.raises(ValueError, match="not authorised"):
        verify_receipt(DOC["receipt"]["artifact"], [es256k_signer("55" * 32).public_key])
    with pytest.raises(ValueError, match="too old"):
        verify_receipt(DOC["receipt"]["artifact"], [KEY["pubCompressed"]], max_age_seconds=60, now=p["issuedAt"] + 61)
    assert verify_jws(DOC["highS"]["compact"], [KEY["pubCompressed"]]).payload["transaction"] == p["transaction"]


def test_tampered_receipts_fail():
    h, p, s = DOC["receipt"]["artifact"]["signature"].split(".")
    other = DOC["jws"]["compact"].split(".")[1]
    for bad in (f"{h}.{other}.{s}", f"{h}.{p}.{s[:-2]}AA", f"{h}.{p}", f"{h}.{p}.{s}=", f"{h}.{p}.{s[:10]}"):
        with pytest.raises(ValueError):
            verify_receipt({"format": "jws", "signature": bad}, [KEY["pubCompressed"]])
    with pytest.raises(ValueError, match="format"):
        verify_receipt({"format": "eip712", "signature": DOC["receipt"]["artifact"]["signature"]}, [KEY["pubCompressed"]])


def _offer_payload():
    import base64
    import json
    body = DOC["offer"]["artifact"]["signature"].split(".")[1]
    return json.loads(base64.urlsafe_b64decode(body + "=" * (-len(body) % 4)))
