"""The pure-Python Sapling primitives against the same vectors the TypeScript package checks
(packages/ycash/test/unit/shielded/decrypt.test.ts): the Zcash test vectors vendored in vectors/sapling
(Pedersen hash, NoteCommit and cmu, note encryption) and the wallet-built ZIP 212 notes of both node
lines (vectors/sapling/sapling_devnet.json, generated by vectors/sapling/generate.ts)."""

import pytest

from tests.conftest import VECTORS, load_vector
from x402_ycash.shielded.sapling import (
    LEAD_BYTE_ZIP212,
    decode_sapling_viewing_key,
    decrypt_note_ciphertext,
    encrypt_note_plaintext,
    extract_u,
    kdf_sapling,
    le_bits,
    memo_bytes,
    note_commitment,
    note_rcm,
    pedersen_hash_to_point,
    prf_expand_to_scalar,
    sapling_ka_agree,
    trial_decrypt_output,
)
from x402_ycash.shielded.sapling.jubjub import R, affine, decode, encode, group_hash, mul
from x402_ycash.tx import parse_tx
from x402_ycash.tx.transaction import OutputDescription

PEDERSEN = load_vector("sapling/sapling_pedersen.json")["vectors"]
ENCRYPTION = load_vector("sapling/sapling_note_encryption.json")["vectors"]
COMPONENTS = load_vector("sapling/sapling_key_components.json")[2:]
GD = b"Zcash_gd"


def le(b: bytes) -> int:
    return int.from_bytes(b, "little")


def rev(h: str) -> bytes:
    """zcashd writes uint256 fields in display order, byte-reversed."""
    return bytes.fromhex(h)[::-1]


def out(cmu: bytes, epk: bytes, c_enc: bytes) -> OutputDescription:
    return OutputDescription(cv=bytes(32), cmu=cmu, ephemeral_key=epk, enc_ciphertext=c_enc, out_ciphertext=bytes(80), zkproof=bytes(192))


NOTE_COMMIT = [v for v in PEDERSEN if v["personalization"] == "NoteCommitment"]


def test_jubjub_order_and_encoding():
    assert R == 0xE7DB4EA6533AFA906673B0101343B00A6682093CCC81082D0970E5ED6F72CB7
    assert decode(bytes([0xFF] * 32)) is None  # v ≥ p
    g = group_hash(bytes(11), GD) or group_hash(bytes([1] + [0] * 10), GD)
    assert g is not None and decode(encode(g)) is not None and encode(decode(encode(g))) == encode(g)  # type: ignore[arg-type]


@pytest.mark.parametrize("v", NOTE_COMMIT, ids=[f"{i}:{len(v['inputBits'])}b" for i, v in enumerate(NOTE_COMMIT)])
def test_pedersen_note_commitment_vectors(v):
    u, w = affine(pedersen_hash_to_point([int(c) for c in v["inputBits"]]))
    assert (u, w) == (int(v["hashU"], 16), int(v["hashV"], 16))


def test_pedersen_merkle_vectors():
    for v in (x for x in PEDERSEN if x["personalization"].startswith("MerkleTree")):
        assert affine(pedersen_hash_to_point([int(c) for c in v["inputBits"]]))[0] == int(v["hashU"], 16)


def test_le_bits():
    assert "".join(map(str, le_bits(bytes([0x01, 0x80])))) == "1000000000000001"


@pytest.mark.parametrize("c", COMPONENTS, ids=range(len(COMPONENTS)))
def test_key_components_cmu(c):
    ivk_hex, d_hex, pkd_hex, note_v, note_r, note_cm = c[6], c[7], c[8], c[9], c[10], c[11]
    gd = group_hash(bytes.fromhex(d_hex), GD)
    assert gd is not None
    pkd = encode(mul(gd, le(rev(ivk_hex))))
    assert pkd == rev(pkd_hex)
    assert extract_u(note_commitment(encode(gd), pkd, int(note_v), le(rev(note_r)))) == rev(note_cm)


@pytest.mark.parametrize("v", ENCRYPTION, ids=range(len(ENCRYPTION)))
def test_note_encryption_vectors(v):
    ivk, epk = le(bytes.fromhex(v["ivk"])), bytes.fromhex(v["epk"])
    assert sapling_ka_agree(ivk, epk).hex() == v["shared_secret"]  # type: ignore[union-attr]
    key = kdf_sapling(bytes.fromhex(v["shared_secret"]), epk)
    assert key.hex() == v["k_enc"]
    assert decrypt_note_ciphertext(key, bytes.fromhex(v["c_enc"])).hex() == v["p_enc"]  # type: ignore[union-attr]
    gd = group_hash(bytes.fromhex(v["default_d"]), GD)
    assert encode(mul(gd, le(bytes.fromhex(v["esk"])))).hex() == v["epk"]  # type: ignore[arg-type]

    o = out(bytes.fromhex(v["cmu"]), epk, bytes.fromhex(v["c_enc"]))
    note = trial_decrypt_output(o, ivk, "ycash:mainnet")
    assert note is not None
    assert (note.lead_byte, note.value, note.diversifier.hex(), note.pkd.hex()) == (1, v["v"], v["default_d"], v["default_pk_d"])
    assert note.rseed.hex() == v["rcm"] and note.memo.hex() == v["memo"]
    assert note.address.startswith("ys1")
    assert memo_bytes(note.memo).hex() == "f6"
    assert trial_decrypt_output(o, ivk + 1, "ycash:mainnet") is None
    bad_cmu = out(bytes([o.cmu[0] ^ 1]) + o.cmu[1:], epk, o.enc_ciphertext)
    assert trial_decrypt_output(bad_cmu, ivk, "ycash:mainnet") is None
    flipped = bytearray(o.enc_ciphertext)
    flipped[100] ^= 1
    assert trial_decrypt_output(out(o.cmu, epk, bytes(flipped)), ivk, "ycash:mainnet") is None


class TestZip212:
    """No published vector covers a 0x02 note end to end: round-trip one (as the TypeScript test does)."""

    v = ENCRYPTION[0]
    ivk = le(bytes.fromhex(v["ivk"]))
    d = bytes.fromhex(v["default_d"])
    rseed = bytes((i * 7 + 3) & 0xFF for i in range(32))
    value = 1_500_000
    memo = ("x402:" + "ab" * 32).encode()

    def encrypt(self, lead: int = LEAD_BYTE_ZIP212, value: int | None = None, esk: int | None = None) -> OutputDescription:
        gd = group_hash(self.d, GD)
        assert gd is not None
        pkd = mul(gd, self.ivk)
        esk = prf_expand_to_scalar(self.rseed, 0x05) if esk is None else esk
        epk = encode(mul(gd, esk))
        shared = encode(mul(mul(pkd, esk), 8))
        pt = bytes([lead]) + self.d + (self.value if value is None else value).to_bytes(8, "little") + self.rseed + self.memo.ljust(512, b"\0")
        rcm = note_rcm(lead, self.rseed)
        assert rcm is not None
        cmu = extract_u(note_commitment(encode(gd), encode(pkd), self.value, rcm))
        return out(cmu, epk, encrypt_note_plaintext(kdf_sapling(shared, epk), pt))

    def test_decrypts_derives_rcm_and_checks_epk(self):
        note = trial_decrypt_output(self.encrypt(), self.ivk, "ycash:regtest")
        assert note is not None and note.lead_byte == 2 and note.value == self.value
        assert memo_bytes(note.memo) == self.memo and note.address.startswith("yregtestsapling1")

    def test_epk_not_from_rseed_is_refused(self):
        assert trial_decrypt_output(self.encrypt(esk=12345), self.ivk, "ycash:regtest") is None

    def test_value_changed_fails_cmu(self):
        assert trial_decrypt_output(self.encrypt(value=self.value + 1), self.ivk, "ycash:regtest") is None

    def test_rcm_and_bad_points(self):
        assert note_rcm(1, bytes([0xFF] * 32)) is None
        assert sapling_ka_agree(self.ivk, bytes([0xFF] * 32)) is None
        assert decrypt_note_ciphertext(bytes(32), bytes(10)) is None


DEVNET = VECTORS / "sapling" / "sapling_devnet.json"
DEVNET_CASES = load_vector("sapling/sapling_devnet.json")["cases"] if DEVNET.exists() else []


@pytest.mark.skipif(not DEVNET_CASES, reason="vectors/sapling/sapling_devnet.json not generated")
@pytest.mark.parametrize("case,pay", [(c, p) for c in DEVNET_CASES for p in c["payments"]],
                         ids=[f"{c['line']}-{p['kind']}" for c in DEVNET_CASES for p in c["payments"]])
def test_wallet_built_notes(case, pay):
    """Each node line's own ZIP 212 notes: exactly one output decrypts, to payTo, with value and memo."""
    key = decode_sapling_viewing_key(case["viewingKey"], "ycash:regtest")
    tx = parse_tx(pay["hex"])
    notes = [(i, n) for i, o in enumerate(tx.shielded_outputs) if (n := trial_decrypt_output(o, key.ivk, "ycash:regtest"))]
    assert [i for i, _ in notes] == [pay["outputIndex"]]
    note = notes[0][1]
    assert note.lead_byte == LEAD_BYTE_ZIP212
    assert note.address == case["payTo"]
    assert note.value == int(pay["amountZat"])
    assert memo_bytes(note.memo).decode() == pay["memo"]
