"""vectors/yed-channel/channel_yed.json (generated by the TypeScript package): the YED channel's
funding TRANSFER, vouchers under the dollar floor with their TRANSFER at vout 2, completed closes and
the refund, reproduced byte for byte; plus the YED layout's rules."""

import pytest

from tests.conftest import load_vector
from x402_ycash.channel import (
    FUNDING_VOUT,
    Channel,
    ChannelScript,
    build_channel_script,
    build_voucher,
    build_yed_funding_tx,
    build_yed_refund,
    channel_script_pubkey,
    check_voucher_shape,
    complete_voucher,
    sign_funding_tx,
    verify_voucher_signature,
    voucher_sighash,
    yed_channel_value,
    yed_voucher_assignments,
    yed_voucher_layout,
)
from x402_ycash.tx import OutPoint, address_to_script, hash160, p2pkh_script, parse_tx, pubkey_from_priv, txid
from x402_ycash.yed import Assignment, TokenCoin, YecCoin, find_payload

DOC = load_vector("yed-channel/channel_yed.json")
BRANCH = int(DOC["branchId"], 16)
CH = DOC["channel"]
C_PRIV, S_PRIV, F_PRIV = (bytes.fromhex(CH[k]) for k in ("clientPriv", "serverPriv", "funderPriv"))
F_SCRIPT = p2pkh_script(hash160(pubkey_from_priv(F_PRIV)))
D = int(CH["depositCents"])
CLOSE_FEE = int(CH["closeFee"])
RS = build_channel_script(ChannelScript(pubkey_from_priv(C_PRIV), pubkey_from_priv(S_PRIV), CH["refundHeight"]))
CLIENT_SCRIPT = bytes.fromhex(CH["clientScript"])
LAYOUT = yed_voucher_layout(D)


def funding():
    f = DOC["funding"]
    token = TokenCoin(OutPoint(f["token"]["outpoint"]["txid"], f["token"]["outpoint"]["vout"]), f["token"]["cents"], int(f["token"]["value"]), F_SCRIPT)
    coin = YecCoin(OutPoint(f["yecCoin"]["outpoint"]["txid"], f["yecCoin"]["outpoint"]["vout"]), int(f["yecCoin"]["value"]), F_SCRIPT)
    built = build_yed_funding_tx(RS, D, CLOSE_FEE, [token], [coin], F_SCRIPT, F_SCRIPT)
    return built, sign_funding_tx(built.tx, built.inputs, [F_PRIV, F_PRIV], BRANCH)


def channel() -> Channel:
    return Channel.from_script(OutPoint(DOC["funding"]["txid"], FUNDING_VOUT), RS, yed_channel_value(CLOSE_FEE), CLOSE_FEE,
                               address_to_script(CH["payTo"], "ycash:regtest"))


def test_channel_and_funding_transfer():
    assert RS.hex() == CH["redeemScript"] and channel_script_pubkey(RS).hex() == CH["scriptPubKey"]
    assert str(yed_channel_value(CLOSE_FEE)) == CH["value"]
    built, signed = funding()
    f = DOC["funding"]
    assert [(a.vout, a.cents) for a in built.assignments] == [(a["vout"], a["cents"]) for a in f["assignments"]]
    assert built.op_return_index == f["opReturnIndex"] and str(built.fee) == f["fee"]
    assert signed.serialize_hex() == f["tx"] and txid(signed) == f["txid"]


@pytest.mark.parametrize("v", DOC["vouchers"], ids=[v["cumulative"] for v in DOC["vouchers"]])
def test_vouchers_and_closes(v):
    ch, cum = channel(), int(v["cumulative"])
    assert [(a.vout, a.cents) for a in yed_voucher_assignments(D, cum)] == [(a["vout"], a["cents"]) for a in v["assignments"]]
    voucher = build_voucher(ch, cum, C_PRIV, BRANCH, CLIENT_SCRIPT, LAYOUT)
    assert voucher.serialize_hex() == v["voucher"]
    assert voucher_sighash(voucher, ch, BRANCH).hex() == v["sighash"]
    close = complete_voucher(parse_tx(v["voucher"]), ch, S_PRIV, BRANCH)
    assert close.serialize_hex() == v["close"] and txid(close) == v["closeTxid"]
    assert [(str(o.value), o.script_pubkey.hex()) for o in close.vout] == [(o["value"], o["scriptPubKey"]) for o in v["outputs"]]
    assert check_voucher_shape(voucher, ch, cum, LAYOUT) is None
    assert check_voucher_shape(close, ch, cum, LAYOUT, allow_completed=True) is None
    assert verify_voucher_signature(voucher, ch, BRANCH)
    found = find_payload([o.script_pubkey for o in voucher.vout])
    assert found is not None and getattr(found, "index", None) == 2


def test_refund():
    r = DOC["refund"]
    refund = build_yed_refund(channel(), D, C_PRIV, CLIENT_SCRIPT, BRANCH)
    assert refund.lock_time == r["lockTime"] and refund.vin[0].sequence == r["sequence"]
    assert refund.serialize_hex() == r["tx"] and txid(refund) == r["txid"]
    found = find_payload([o.script_pubkey for o in refund.vout])
    assert [(a.vout, a.cents) for a in found.payload.assignments] == [(1, D)]  # type: ignore[union-attr]


def test_layout_rules():
    ch = channel()
    with pytest.raises(ValueError, match="below the \\$1.00 floor"):
        LAYOUT(ch, 99, CLIENT_SCRIPT)
    with pytest.raises(ValueError, match="exceeds the deposit"):
        LAYOUT(ch, D + 1, CLIENT_SCRIPT)
    with pytest.raises(ValueError, match="client output script"):
        LAYOUT(ch, 100, None)
    with pytest.raises(ValueError, match="must not pay payTo"):
        LAYOUT(ch, 100, ch.pay_to_script)
    wrong_v = Channel(ch.outpoint, ch.redeem_script, ch.value + 1, ch.close_fee, ch.pay_to_script, ch.client_pubkey, ch.server_pubkey, ch.refund_height)
    with pytest.raises(ValueError, match="2 × TOKEN_VALUE"):
        LAYOUT(wrong_v, 100, CLIENT_SCRIPT)
    # a remainder in (0, $1.00) goes to the server: one assignment of all of D
    assert yed_voucher_assignments(D, D - 1) == [Assignment(0, D)]
    # a voucher whose TRANSFER differs (here: burning) is not the layout's
    v = build_voucher(ch, 100, C_PRIV, BRANCH, CLIENT_SCRIPT, yed_voucher_layout(D + 100))
    assert check_voucher_shape(v, ch, 100, LAYOUT) == "outputs"
