//! An in-process fake lightwalletd for the unit tests: `CompactTxStreamer` and (optionally)
//! `YellowbackStreamer.GetChainInfo` on a loopback port, recording which methods were called.
//! The tests prove an injected channel carries every call (`wallet::Options::channel`, YEW Z-3).

use std::net::SocketAddr;
use std::sync::{Arc, Mutex};

use tonic::transport::server::TcpIncoming;
use tonic::transport::{Channel, Endpoint, Server};
use tonic::{Request, Response, Status};

/// Server stubs generated by build.rs from the vendored protos (OUT_DIR/fake).
#[allow(clippy::all)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/fake/cash.z.wallet.sdk.rpc.rs"));
}

use pb::compact_tx_streamer_server::{CompactTxStreamer, CompactTxStreamerServer};
use pb::yellowback_streamer_server::{YellowbackStreamer, YellowbackStreamerServer};
use tonic::codegen::BoxStream;

pub const TIP: u64 = 120;
pub const NEXT_BRANCH: &str = "19bd2d2f";

#[derive(Clone, Default)]
pub struct Fake {
    pub calls: Arc<Mutex<Vec<&'static str>>>,
}

impl Fake {
    fn hit(&self, method: &'static str) {
        self.calls.lock().expect("calls").push(method);
    }

    pub fn called(&self) -> Vec<&'static str> {
        self.calls.lock().expect("calls").clone()
    }
}

#[tonic::async_trait]
impl CompactTxStreamer for Fake {
    async fn get_lightd_info(
        &self,
        _: Request<pb::Empty>,
    ) -> Result<Response<pb::LightdInfo>, Status> {
        self.hit("GetLightdInfo");
        Ok(Response::new(pb::LightdInfo {
            chain_name: "regtest".into(),
            block_height: TIP,
            consensus_branch_id: "e9ff75a6".into(),
            ..Default::default()
        }))
    }

    async fn get_latest_block(
        &self,
        _: Request<pb::ChainSpec>,
    ) -> Result<Response<pb::BlockId>, Status> {
        self.hit("GetLatestBlock");
        Ok(Response::new(pb::BlockId {
            height: TIP,
            hash: vec![0; 32],
        }))
    }

    async fn get_tree_state(
        &self,
        req: Request<pb::BlockId>,
    ) -> Result<Response<pb::TreeState>, Status> {
        self.hit("GetTreeState");
        let height = req.into_inner().height;
        Ok(Response::new(pb::TreeState {
            network: "regtest".into(),
            height,
            tree: "000000".into(),
            ..Default::default()
        }))
    }

    async fn get_block_range(
        &self,
        req: Request<pb::BlockRange>,
    ) -> Result<Response<BoxStream<pb::CompactBlock>>, Status> {
        self.hit("GetBlockRange");
        let r = req.into_inner();
        let (start, end) = (
            r.start.unwrap_or_default().height,
            r.end.unwrap_or_default().height,
        );
        let blocks = (start..=end).map(|height| {
            Ok(pb::CompactBlock {
                height,
                ..Default::default()
            })
        });
        Ok(Response::new(Box::pin(futures_util::stream::iter(blocks))))
    }

    async fn get_mempool_tx(
        &self,
        _: Request<pb::Exclude>,
    ) -> Result<Response<BoxStream<pb::CompactTx>>, Status> {
        self.hit("GetMempoolTx");
        let tx = pb::CompactTx {
            index: 0,
            hash: vec![7; 32],
            ..Default::default()
        };
        Ok(Response::new(Box::pin(futures_util::stream::iter([Ok(
            tx,
        )]))))
    }

    async fn send_transaction(
        &self,
        req: Request<pb::RawTransaction>,
    ) -> Result<Response<pb::SendResponse>, Status> {
        self.hit("SendTransaction");
        let data = req.into_inner().data;
        // lightwalletd's success reply: the node's JSON result (the quoted txid) in errorMessage.
        Ok(Response::new(pb::SendResponse {
            error_code: 0,
            error_message: format!("\"{}\"", hex::encode(&data)),
        }))
    }
}

#[tonic::async_trait]
impl YellowbackStreamer for Fake {
    async fn get_chain_info(
        &self,
        _: Request<pb::Empty>,
    ) -> Result<Response<pb::YedChainInfo>, Status> {
        self.hit("GetChainInfo");
        Ok(Response::new(pb::YedChainInfo {
            block_height: TIP,
            next_block_branch_id: NEXT_BRANCH.into(),
            ..Default::default()
        }))
    }
}

/// Starts the fake on a free loopback port and returns it with a plaintext channel to it: the
/// kind of channel a host builds itself. `yellowback: false` leaves out `YellowbackStreamer`,
/// so `GetChainInfo` answers UNIMPLEMENTED like a pre-0b3448e server.
pub async fn start(yellowback: bool) -> (Fake, Channel, SocketAddr) {
    let fake = Fake::default();
    let incoming = TcpIncoming::bind("127.0.0.1:0".parse().expect("addr")).expect("bind");
    let addr = incoming.local_addr().expect("local addr");
    let router = Server::builder()
        .add_service(CompactTxStreamerServer::new(fake.clone()))
        .add_optional_service(yellowback.then(|| YellowbackStreamerServer::new(fake.clone())));
    tokio::spawn(router.serve_with_incoming(incoming));
    let channel = Endpoint::from_shared(format!("http://{addr}"))
        .expect("endpoint")
        .connect()
        .await
        .expect("connect to the fake");
    (fake, channel, addr)
}

mod tests {
    use super::*;
    use crate::lwd::{self, TlsRoots};
    use crate::wallet::{Options, Wallet};
    use crate::YcashNetwork;
    use zcash_protocol::consensus::BlockHeight;

    /// A port nothing listens on: if the wallet dialed `lwd` instead of using the channel, open
    /// would fail with a connection error.
    const UNDIALED: &str = "grpc://127.0.0.1:1";

    fn data_dir(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "x402-light-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .expect("clock")
                .as_nanos()
        ));
        let _ = std::fs::remove_dir_all(&dir);
        dir
    }

    #[tokio::test]
    async fn wallet_uses_the_injected_channel_for_every_call() {
        let (fake, channel, _) = start(true).await;
        let dir = data_dir("inject");
        let mut w = Wallet::open(Options {
            channel: Some(channel),
            ..Options::new(&dir, UNDIALED, YcashNetwork::devnet_regtest())
        })
        .await
        .expect("open never dials lwd when a channel is injected");

        let status = w.status(1).await.expect("status");
        assert_eq!(status.lwdHeight, TIP as u32);
        assert_eq!(status.lwdLatestHeight, TIP as u32);
        assert_eq!(status.lwd, UNDIALED, "lwd stays the label status reports");

        let sent = w.broadcast("00ff").await.expect("broadcast");
        assert_eq!(sent.txid, "00ff");

        // A host call over the wallet's own channel reaches the same server.
        let mut client = lwd::client(w.channel().clone());
        let info = lwd::branch_info(&mut client, w.channel())
            .await
            .expect("branch");
        assert!(info.next_block);

        assert_eq!(
            fake.called(),
            [
                "GetLightdInfo",
                "GetLatestBlock",
                "SendTransaction",
                "GetChainInfo"
            ]
        );
        drop(w);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn every_lightwalletd_call_goes_over_a_host_channel() {
        let (fake, channel, _) = start(true).await;
        let mut client = lwd::client(channel.clone());

        let branch = lwd::branch_info(&mut client, &channel)
            .await
            .expect("chain info");
        assert_eq!(
            (branch.height, branch.branch_id_hex.as_str()),
            (TIP as u32, NEXT_BRANCH)
        );
        assert!(branch.next_block);

        let ts = lwd::tree_state(&mut client, BlockHeight::from_u32(99))
            .await
            .expect("tree");
        assert_eq!(ts.height, 99);

        let blocks = lwd::block_range(&mut client, 5u32.into(), 7u32.into())
            .await
            .expect("range");
        assert_eq!(
            blocks.iter().map(|b| b.height).collect::<Vec<_>>(),
            [5, 6, 7]
        );

        let mut stream = lwd::block_stream(&mut client, 1u32.into(), 2u32.into())
            .await
            .expect("s");
        let mut n = 0;
        while stream.message().await.expect("message").is_some() {
            n += 1;
        }
        assert_eq!(n, 2);

        let mempool = lwd::mempool(&mut client).await.expect("mempool");
        assert_eq!(mempool.len(), 1);
        assert_eq!(mempool[0].txid, vec![7; 32]);

        assert_eq!(
            lwd::latest_height(&mut client).await.expect("tip"),
            BlockHeight::from_u32(120)
        );

        assert_eq!(
            fake.called(),
            [
                "GetChainInfo",
                "GetTreeState",
                "GetBlockRange",
                "GetBlockRange",
                "GetMempoolTx",
                "GetLatestBlock"
            ]
        );
    }

    #[tokio::test]
    async fn branch_info_falls_back_to_the_chaintip_without_yellowback_streamer() {
        let (fake, channel, _) = start(false).await;
        let mut client = lwd::client(channel.clone());
        let branch = lwd::branch_info(&mut client, &channel)
            .await
            .expect("fallback");
        assert!(!branch.next_block);
        assert_eq!(branch.branch_id_hex, "e9ff75a6");
        assert_eq!(fake.called(), ["GetLightdInfo"]);
    }

    #[tokio::test]
    async fn the_url_path_still_dials() {
        let (fake, _host_channel, addr) = start(true).await;
        let dir = data_dir("url");
        let mut w = Wallet::open(Options::new(
            &dir,
            addr.to_string(),
            YcashNetwork::devnet_regtest(),
        ))
        .await
        .expect("loopback host:port is plaintext");
        w.status(1).await.expect("status");
        assert_eq!(fake.called(), ["GetLightdInfo", "GetLatestBlock"]);
        drop(w);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn tls_roots_parse_and_default_per_target() {
        assert_eq!("native".parse::<TlsRoots>(), Ok(TlsRoots::Native));
        assert_eq!("webpki".parse::<TlsRoots>(), Ok(TlsRoots::Webpki));
        assert!("system".parse::<TlsRoots>().is_err());
        let expected = if cfg!(any(target_os = "ios", target_os = "android")) {
            TlsRoots::Webpki
        } else {
            TlsRoots::Native
        };
        assert_eq!(TlsRoots::default(), expected);
    }

    /// Both root stores are compiled in, so either can be chosen at run time on any target.
    #[test]
    fn tls_endpoints_build_with_either_root_store() {
        for roots in [TlsRoots::Native, TlsRoots::Webpki] {
            let ep = lwd::endpoint("grpcs://lwd.example:9067", roots).expect("tls endpoint");
            assert_eq!(ep.uri().scheme_str(), Some("https"));
        }
        let ep = lwd::endpoint("grpc://127.0.0.1:9067", TlsRoots::Webpki).expect("plain");
        assert_eq!(ep.uri().scheme_str(), Some("http"));
    }
}
