//! An in-process fake lightwalletd for the unit tests: `CompactTxStreamer` and (optionally)
//! `YellowbackStreamer.GetChainInfo` on a loopback port, recording which methods were called.
//! The tests prove an injected channel carries every call (`wallet::Options::channel`, YEW Z-3).
//! With a [`Chain`] it also serves a scannable chain of empty blocks that a test can fork, for the
//! reorg tests in `src/sync.rs`.

use std::net::SocketAddr;
use std::sync::{Arc, Mutex};

use tonic::transport::server::TcpIncoming;
use tonic::transport::{Channel, Endpoint, Server};
use tonic::{Request, Response, Status};

/// Server stubs generated by build.rs from the vendored protos (OUT_DIR/fake).
#[allow(clippy::all)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/fake/cash.z.wallet.sdk.rpc.rs"));
}

use pb::compact_tx_streamer_server::{CompactTxStreamer, CompactTxStreamerServer};
use pb::yellowback_streamer_server::{YellowbackStreamer, YellowbackStreamerServer};
use tonic::codegen::BoxStream;

pub const TIP: u64 = 120;
pub const NEXT_BRANCH: &str = "19bd2d2f";

/// The devnet's branch id (X-F9), served as the chaintip's when a [`Chain`] is set so the
/// wallet's branch check at sync passes.
pub const CANOPY: &str = "19bd2d2f";

#[derive(Clone, Default)]
pub struct Fake {
    pub calls: Arc<Mutex<Vec<&'static str>>>,
    /// `GetTreeState` heights, in call order.
    pub tree_states: Arc<Mutex<Vec<u64>>>,
    /// When set, a scannable chain replaces the canned answers.
    pub chain: Arc<Mutex<Option<Chain>>>,
}

/// A scannable chain whose block hashes depend on the height and on the branch a block belongs
/// to: `fork(h, ..)` replaces every block from `h` up, the way `invalidateblock` + mining a
/// competing branch does on a node. Blocks in `outputs` carry one Sapling output nobody can
/// decrypt (the store checkpoints only blocks with note commitments, so they decide where a
/// rewind may land); the others are empty. Tree states are computed from those outputs.
#[derive(Clone, Debug, Default)]
pub struct Chain {
    pub tip: u64,
    /// (first replaced height, branch number) of each fork so far, oldest first.
    pub forks: Vec<(u64, u8)>,
    /// Heights holding one Sapling output, on every branch.
    pub outputs: std::collections::BTreeSet<u64>,
}

impl Chain {
    pub fn new(tip: u64) -> Self {
        Chain {
            tip,
            ..Default::default()
        }
    }

    /// Replaces blocks `from..` with a new branch reaching `tip`.
    pub fn fork(&mut self, from: u64, tip: u64) {
        let branch = self.forks.len() as u8 + 1;
        self.forks.push((from, branch));
        self.tip = tip;
    }

    fn branch(&self, height: u64) -> u8 {
        self.forks
            .iter()
            .rev()
            .find(|(from, _)| height >= *from)
            .map_or(0, |(_, b)| *b)
    }

    /// The block hash in internal byte order: height, then the branch.
    pub fn hash(&self, height: u64) -> [u8; 32] {
        let mut h = [0u8; 32];
        h[..8].copy_from_slice(&height.to_le_bytes());
        h[8] = self.branch(height);
        h[31] = 0x5a;
        h
    }

    /// The note commitment of the output at `height`: a small field element, distinct per
    /// height and branch.
    fn cmu(&self, height: u64) -> [u8; 32] {
        let mut c = [0u8; 32];
        c[..8].copy_from_slice(&height.to_le_bytes());
        c[8] = self.branch(height);
        c[9] = 1;
        c
    }

    fn block(&self, height: u64) -> pb::CompactBlock {
        let vtx = if self.outputs.contains(&height) {
            vec![pb::CompactTx {
                index: 1,
                hash: self.cmu(height).to_vec(),
                outputs: vec![pb::CompactOutput {
                    cmu: self.cmu(height).to_vec(),
                    epk: vec![0; 32],
                    ciphertext: vec![0; 52],
                }],
                ..Default::default()
            }]
        } else {
            vec![]
        };
        pb::CompactBlock {
            height,
            hash: self.hash(height).to_vec(),
            prev_hash: if height == 0 {
                vec![0; 32]
            } else {
                self.hash(height - 1).to_vec()
            },
            time: 1_600_000_000 + height as u32,
            vtx,
            ..Default::default()
        }
    }

    /// The Sapling tree after `height`, hex-encoded as `z_gettreestate` returns it.
    fn tree_hex(&self, height: u64) -> String {
        let mut tree = sapling::CommitmentTree::empty();
        for h in self.outputs.range(..=height) {
            let node = Option::from(sapling::Node::from_bytes(self.cmu(*h))).expect("valid cmu");
            tree.append(node).expect("tree not full");
        }
        let mut buf = vec![];
        zcash_primitives::merkle_tree::write_commitment_tree(&tree, &mut buf).expect("write");
        hex::encode(buf)
    }
}

impl Fake {
    fn hit(&self, method: &'static str) {
        self.calls.lock().expect("calls").push(method);
    }

    pub fn called(&self) -> Vec<&'static str> {
        self.calls.lock().expect("calls").clone()
    }

    pub fn chain(&self) -> Option<Chain> {
        self.chain.lock().expect("chain").clone()
    }

    /// Serves `chain` from now on.
    pub fn set_chain(&self, chain: Chain) {
        *self.chain.lock().expect("chain") = Some(chain);
    }

    /// Applies `f` to the served chain (e.g. a fork).
    pub fn with_chain(&self, f: impl FnOnce(&mut Chain)) {
        f(self
            .chain
            .lock()
            .expect("chain")
            .as_mut()
            .expect("a chain is set"));
    }
}

#[tonic::async_trait]
impl CompactTxStreamer for Fake {
    async fn get_lightd_info(
        &self,
        _: Request<pb::Empty>,
    ) -> Result<Response<pb::LightdInfo>, Status> {
        self.hit("GetLightdInfo");
        if let Some(chain) = self.chain() {
            return Ok(Response::new(pb::LightdInfo {
                chain_name: "regtest".into(),
                block_height: chain.tip,
                consensus_branch_id: CANOPY.into(),
                ..Default::default()
            }));
        }
        Ok(Response::new(pb::LightdInfo {
            chain_name: "regtest".into(),
            block_height: TIP,
            consensus_branch_id: "e9ff75a6".into(),
            ..Default::default()
        }))
    }

    async fn get_latest_block(
        &self,
        _: Request<pb::ChainSpec>,
    ) -> Result<Response<pb::BlockId>, Status> {
        self.hit("GetLatestBlock");
        if let Some(chain) = self.chain() {
            return Ok(Response::new(pb::BlockId {
                height: chain.tip,
                hash: chain.hash(chain.tip).to_vec(),
            }));
        }
        Ok(Response::new(pb::BlockId {
            height: TIP,
            hash: vec![0; 32],
        }))
    }

    async fn get_tree_state(
        &self,
        req: Request<pb::BlockId>,
    ) -> Result<Response<pb::TreeState>, Status> {
        self.hit("GetTreeState");
        let height = req.into_inner().height;
        self.tree_states.lock().expect("tree states").push(height);
        if let Some(chain) = self.chain() {
            if height > chain.tip {
                return Err(Status::out_of_range("above the tip"));
            }
            let mut display = chain.hash(height);
            display.reverse();
            return Ok(Response::new(pb::TreeState {
                network: "regtest".into(),
                height,
                hash: hex::encode(display),
                tree: chain.tree_hex(height),
                ..Default::default()
            }));
        }
        Ok(Response::new(pb::TreeState {
            network: "regtest".into(),
            height,
            tree: "000000".into(),
            ..Default::default()
        }))
    }

    async fn get_block_range(
        &self,
        req: Request<pb::BlockRange>,
    ) -> Result<Response<BoxStream<pb::CompactBlock>>, Status> {
        self.hit("GetBlockRange");
        let r = req.into_inner();
        let (start, end) = (
            r.start.unwrap_or_default().height,
            r.end.unwrap_or_default().height,
        );
        if let Some(chain) = self.chain() {
            let blocks: Vec<_> = (start..=end.min(chain.tip))
                .map(|h| Ok(chain.block(h)))
                .collect();
            return Ok(Response::new(Box::pin(futures_util::stream::iter(blocks))));
        }
        let blocks = (start..=end).map(|height| {
            Ok(pb::CompactBlock {
                height,
                ..Default::default()
            })
        });
        Ok(Response::new(Box::pin(futures_util::stream::iter(blocks))))
    }

    async fn get_mempool_tx(
        &self,
        _: Request<pb::Exclude>,
    ) -> Result<Response<BoxStream<pb::CompactTx>>, Status> {
        self.hit("GetMempoolTx");
        let tx = pb::CompactTx {
            index: 0,
            hash: vec![7; 32],
            ..Default::default()
        };
        Ok(Response::new(Box::pin(futures_util::stream::iter([Ok(
            tx,
        )]))))
    }

    async fn send_transaction(
        &self,
        req: Request<pb::RawTransaction>,
    ) -> Result<Response<pb::SendResponse>, Status> {
        self.hit("SendTransaction");
        let data = req.into_inner().data;
        // lightwalletd's success reply: the node's JSON result (the quoted txid) in errorMessage.
        Ok(Response::new(pb::SendResponse {
            error_code: 0,
            error_message: format!("\"{}\"", hex::encode(&data)),
        }))
    }
}

#[tonic::async_trait]
impl YellowbackStreamer for Fake {
    async fn get_chain_info(
        &self,
        _: Request<pb::Empty>,
    ) -> Result<Response<pb::YedChainInfo>, Status> {
        self.hit("GetChainInfo");
        Ok(Response::new(pb::YedChainInfo {
            block_height: TIP,
            next_block_branch_id: NEXT_BRANCH.into(),
            ..Default::default()
        }))
    }
}

/// Starts the fake on a free loopback port and returns it with a plaintext channel to it: the
/// kind of channel a host builds itself. `yellowback: false` leaves out `YellowbackStreamer`,
/// so `GetChainInfo` answers UNIMPLEMENTED like a pre-0b3448e server.
pub async fn start(yellowback: bool) -> (Fake, Channel, SocketAddr) {
    let fake = Fake::default();
    let incoming = TcpIncoming::bind("127.0.0.1:0".parse().expect("addr")).expect("bind");
    let addr = incoming.local_addr().expect("local addr");
    let router = Server::builder()
        .add_service(CompactTxStreamerServer::new(fake.clone()))
        .add_optional_service(yellowback.then(|| YellowbackStreamerServer::new(fake.clone())));
    tokio::spawn(router.serve_with_incoming(incoming));
    let channel = Endpoint::from_shared(format!("http://{addr}"))
        .expect("endpoint")
        .connect()
        .await
        .expect("connect to the fake");
    (fake, channel, addr)
}

pub(crate) fn temp_data_dir(name: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "x402-light-{name}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("clock")
            .as_nanos()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    dir
}

mod tests {
    use super::*;
    use crate::lwd::{self, TlsRoots};
    use crate::wallet::{Options, Wallet};
    use crate::YcashNetwork;
    use zcash_protocol::consensus::BlockHeight;

    /// A port nothing listens on: if the wallet dialed `lwd` instead of using the channel, open
    /// would fail with a connection error.
    const UNDIALED: &str = "grpc://127.0.0.1:1";

    fn data_dir(name: &str) -> std::path::PathBuf {
        temp_data_dir(name)
    }

    #[tokio::test]
    async fn wallet_uses_the_injected_channel_for_every_call() {
        let (fake, channel, _) = start(true).await;
        let dir = data_dir("inject");
        let mut w = Wallet::open(Options {
            channel: Some(channel),
            ..Options::new(&dir, UNDIALED, YcashNetwork::devnet_regtest())
        })
        .await
        .expect("open never dials lwd when a channel is injected");

        let status = w.status(1).await.expect("status");
        assert_eq!(status.lwdHeight, TIP as u32);
        assert_eq!(status.lwdLatestHeight, TIP as u32);
        assert_eq!(status.lwd, UNDIALED, "lwd stays the label status reports");

        let sent = w.broadcast("00ff").await.expect("broadcast");
        assert_eq!(sent.txid, "00ff");

        // A host call over the wallet's own channel reaches the same server.
        let mut client = lwd::client(w.channel().clone());
        let info = lwd::branch_info(&mut client, w.channel())
            .await
            .expect("branch");
        assert!(info.next_block);

        assert_eq!(
            fake.called(),
            [
                "GetLightdInfo",
                "GetLatestBlock",
                "SendTransaction",
                "GetChainInfo"
            ]
        );
        drop(w);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn every_lightwalletd_call_goes_over_a_host_channel() {
        let (fake, channel, _) = start(true).await;
        let mut client = lwd::client(channel.clone());

        let branch = lwd::branch_info(&mut client, &channel)
            .await
            .expect("chain info");
        assert_eq!(
            (branch.height, branch.branch_id_hex.as_str()),
            (TIP as u32, NEXT_BRANCH)
        );
        assert!(branch.next_block);

        let ts = lwd::tree_state(&mut client, BlockHeight::from_u32(99))
            .await
            .expect("tree");
        assert_eq!(ts.height, 99);

        let blocks = lwd::block_range(&mut client, 5u32.into(), 7u32.into())
            .await
            .expect("range");
        assert_eq!(
            blocks.iter().map(|b| b.height).collect::<Vec<_>>(),
            [5, 6, 7]
        );

        let mut stream = lwd::block_stream(&mut client, 1u32.into(), 2u32.into())
            .await
            .expect("s");
        let mut n = 0;
        while stream.message().await.expect("message").is_some() {
            n += 1;
        }
        assert_eq!(n, 2);

        let mempool = lwd::mempool(&mut client).await.expect("mempool");
        assert_eq!(mempool.len(), 1);
        assert_eq!(mempool[0].txid, vec![7; 32]);

        assert_eq!(
            lwd::latest_height(&mut client).await.expect("tip"),
            BlockHeight::from_u32(120)
        );

        assert_eq!(
            fake.called(),
            [
                "GetChainInfo",
                "GetTreeState",
                "GetBlockRange",
                "GetBlockRange",
                "GetMempoolTx",
                "GetLatestBlock"
            ]
        );
    }

    #[tokio::test]
    async fn branch_info_falls_back_to_the_chaintip_without_yellowback_streamer() {
        let (fake, channel, _) = start(false).await;
        let mut client = lwd::client(channel.clone());
        let branch = lwd::branch_info(&mut client, &channel)
            .await
            .expect("fallback");
        assert!(!branch.next_block);
        assert_eq!(branch.branch_id_hex, "e9ff75a6");
        assert_eq!(fake.called(), ["GetLightdInfo"]);
    }

    #[tokio::test]
    async fn the_url_path_still_dials() {
        let (fake, _host_channel, addr) = start(true).await;
        let dir = data_dir("url");
        let mut w = Wallet::open(Options::new(
            &dir,
            addr.to_string(),
            YcashNetwork::devnet_regtest(),
        ))
        .await
        .expect("loopback host:port is plaintext");
        w.status(1).await.expect("status");
        assert_eq!(fake.called(), ["GetLightdInfo", "GetLatestBlock"]);
        drop(w);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[tokio::test]
    async fn a_second_wallet_on_the_same_data_dir_is_refused() {
        let (_fake, channel, _) = start(true).await;
        let dir = data_dir("lock");
        let opts = || Options {
            channel: Some(channel.clone()),
            ..Options::new(&dir, UNDIALED, YcashNetwork::devnet_regtest())
        };
        let first = Wallet::open(opts()).await.expect("first open");
        match Wallet::open(opts()).await {
            Err(crate::wallet::Error::Locked(d)) => assert_eq!(d, dir),
            Err(e) => panic!("expected Locked, got {e}"),
            Ok(_) => panic!("a second wallet opened the same data directory"),
        }
        drop(first);
        Wallet::open(opts())
            .await
            .expect("reopens once the first is dropped");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn build_needs_the_wallet_at_the_server_tip() {
        use crate::wallet::{check_tip, Error};
        let server = lwd::BranchInfo {
            height: 120,
            branch_id_hex: NEXT_BRANCH.into(),
            next_block: true,
        };
        let at = |h: u32| check_tip(Some(BlockHeight::from_u32(h)), &server);
        assert_eq!(at(120).expect("at tip"), BlockHeight::from_u32(120));
        for (wallet, h) in [
            (Some(119), at(119)),
            (Some(121), at(121)),
            (None, check_tip(None, &server)),
        ] {
            match h {
                Err(Error::NotAtServerTip {
                    wallet: w,
                    server: 120,
                }) => assert_eq!(w, wallet),
                other => panic!("expected NotAtServerTip, got {other:?}"),
            }
        }
    }

    #[test]
    fn build_signs_with_vault_only_when_our_parameters_have_it() {
        use crate::wallet::{check_branch, Error};
        use zcash_protocol::consensus::BranchId;
        // The node's next block (103) is the first Vault block.
        let next = |id: &str| lwd::BranchInfo {
            height: 102,
            branch_id_hex: id.into(),
            next_block: true,
        };
        let target = BlockHeight::from_u32(103);
        let vault = YcashNetwork::devnet_regtest()
            .with_upgrades("vault=103")
            .unwrap();
        assert_eq!(
            check_branch(&vault, &next("6d5b7a31"), target).unwrap(),
            BranchId::Vault
        );
        // Parameters without Vault would sign Canopy at 103, which the node refuses: refuse first.
        match check_branch(&YcashNetwork::devnet_regtest(), &next("6d5b7a31"), target) {
            Err(Error::Server(m)) => assert!(m.contains("--upgrades"), "{m}"),
            other => panic!("expected a branch mismatch, got {other:?}"),
        }
        // A server still on Canopy for 103 disagrees with Vault parameters the same way.
        assert!(check_branch(&vault, &next(CANOPY), target).is_err());
        // The block before: both agree on Canopy.
        let before = lwd::BranchInfo {
            height: 101,
            branch_id_hex: CANOPY.into(),
            next_block: true,
        };
        assert_eq!(
            check_branch(&vault, &before, BlockHeight::from_u32(102)).unwrap(),
            BranchId::Canopy
        );
        // A chaintip-only server (X-F71) at 102 says Canopy: our Canopy at 102 agrees, and the
        // signature is still Vault's (our parameters at the target), which the node wants.
        let tip_only = lwd::BranchInfo {
            height: 102,
            branch_id_hex: CANOPY.into(),
            next_block: false,
        };
        assert_eq!(
            check_branch(&vault, &tip_only, target).unwrap(),
            BranchId::Vault
        );
    }

    #[test]
    fn tls_roots_parse_and_default_per_target() {
        assert_eq!("native".parse::<TlsRoots>(), Ok(TlsRoots::Native));
        assert_eq!("webpki".parse::<TlsRoots>(), Ok(TlsRoots::Webpki));
        assert!("system".parse::<TlsRoots>().is_err());
        let expected = if cfg!(any(target_os = "ios", target_os = "android")) {
            TlsRoots::Webpki
        } else {
            TlsRoots::Native
        };
        assert_eq!(TlsRoots::default(), expected);
    }

    /// Both root stores are compiled in, so either can be chosen at run time on any target.
    #[test]
    fn tls_endpoints_build_with_either_root_store() {
        for roots in [TlsRoots::Native, TlsRoots::Webpki] {
            let ep = lwd::endpoint("grpcs://lwd.example:9067", roots).expect("tls endpoint");
            assert_eq!(ep.uri().scheme_str(), Some("https"));
        }
        let ep = lwd::endpoint("grpc://127.0.0.1:9067", TlsRoots::Webpki).expect("plain");
        assert_eq!(ep.uri().scheme_str(), Some("http"));
    }
}
